name: hive2sql_annotations
description: Annotations for hive2sql.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.8.1 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
